{
 "title": "OpenVPN Server",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [ "openvpn" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(count_values(\"connection_time\", count_over_time(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))by(common_name)>1)",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_up{job=\"openvpn-exporter\"}"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table",
   "gridPos": { "h": 21, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(label_replace(openvpn_server_client_received_bytes_total{job=\"openvpn-exporter\",common_name!=\"UNDEF\"}, \"connection_time\", \"time() - ${1}000\", \"connection_time2\", \"(.*)\")) by (common_name, connection_time, virtual_address, real_address)"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_server_connected_clients{job=\"openvpn-exporter\"}",
     "legendFormat": "Client(s)"
    }
   ]
  },
  {
   "title": "Status Update Since",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-openvpn_status_update_time_seconds{job=\"openvpn-exporter\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openvpn_server_client_received_bytes_total{job=\"openvpn-exporter\",common_name=~\"[a-zA-Z0-9]*\"}) or absent(count(openvpn_server_client_received_bytes_total{job=\"openvpn-exporter\",common_name=~\"[a-zA-Z0-9]*\"}))-1"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Top 6 Client Network Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_received_bytes_total{job=\"openvpn-exporter\",common_name!=\"UNDEF\"}[2m])) by (common_name))",
     "legendFormat": "{{ common_name }} - Rx"
    },
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_sent_bytes_total{job=\"openvpn-exporter\",common_name!=\"UNDEF\"}[2m])) by (common_name))",
     "legendFormat": "{{ common_name }} - Tx"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort(sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Clients" }
   ],
   "targets": [
    {
     "expr": "sum(openvpn_server_connected_clients{job=\"openvpn-exporter\"})"
    }
   ]
  }
 ]
}