{
 "title": "Seagate Lacie 2BIG NAS SNMP",
 "description": "A Dashboard for Seagate Lacie NAS based on SNMP and Prometheus",
 "tags": [
  "nas",
  "seagate"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "query_result(sum by (instance)(ifInOctets{job=\"snmp-exporter\"}))"
    }
   },
   {
    "name": "snDiskIndex",
    "query": {
     "query": "query_result(snDiskSlot{job=\"snmp-exporter\",instance=\"$Device\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(ssCpuIdle{instance=\"$Device\",job=\"snmp-exporter\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((snMemPhysTot{instance=\"$Device\",job=\"snmp-exporter\"} - snMemPhysUsed{instance=\"$Device\",job=\"snmp-exporter\"}) / (snMemPhysTot{instance=\"$Device\",job=\"snmp-exporter\"})) * 100",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snVolPercentUsed{instance=\"$Device\",job=\"snmp-exporter\",snVolIndex=\"3\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"snmp-exporter\",instance=\"$Device\"} / 100",
     "legendFormat": "Second"
    }
   ]
  },
  {
   "title": "Disks Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "snDiskSize{instance=\"$Device\",job=\"snmp-exporter\",snDiskIndex=~\"$snDiskIndex\"}",
     "legendFormat": "size"
    },
    {
     "expr": "snDiskModel{instance=\"$Device\",job=\"snmp-exporter\",snDiskIndex=~\"$snDiskIndex\"}",
     "legendFormat": "model"
    },
    {
     "expr": "snDiskTemperature{instance=\"$Device\",job=\"snmp-exporter\",snDiskIndex=~\"$snDiskIndex\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "snMemPhysFree{instance=\"$Device\",job=\"snmp-exporter\"} * 1024",
     "legendFormat": "Free"
    },
    {
     "expr": "snMemPhysCached{instance=\"$Device\",job=\"snmp-exporter\"} * 1024",
     "legendFormat": "Cached"
    },
    {
     "expr": "snMemPhysUsed{instance=\"$Device\",job=\"snmp-exporter\"} * 1024",
     "legendFormat": "Used"
    },
    {
     "expr": "snMemPhysTot{instance=\"$Device\",job=\"snmp-exporter\"} * 1024",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Average nb processes" }
   ],
   "targets": [
    {
     "expr": "avg(laLoadInt{laIndex=\"1\",instance=\"$Device\",job=\"snmp-exporter\"}) / 100",
     "legendFormat": "last 1 min"
    },
    {
     "expr": "avg(laLoadInt{laIndex=\"2\",instance=\"$Device\",job=\"snmp-exporter\"}) / 100",
     "legendFormat": "last 5 min"
    },
    {
     "expr": "avg(laLoadInt{laIndex=\"3\",instance=\"$Device\",job=\"snmp-exporter\"}) / 100",
     "legendFormat": "last 15 min"
    }
   ]
  },
  {
   "title": "Traffic Interface",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 10 },
   "repeat": "Interface",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifInOctets{job='snmp-exporter',instance='$Device',ifIndex='2'}[5m]) ",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifOutOctets{job='snmp-exporter',instance='$Device',ifIndex='2'}[5m]) ",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}